### ISSUE TITLE
DISA October Meeting To-Do List 

### ISSUE THREAD

**Issue by mcakkerman** [Brown-University-Library/disa_dj_project#28]
- [x] Get general search working 

- [x] Confirm data is correct 

- [x] Add fields: Race, Status, and Date 

- [x] Make fields drop-downs 

- [x] Format details modal -- add individual data table 

- [x] Encode/decode special characters consistently 

- [x] Ensure that enslavers can show up

- [x] Get it onto production

- [x] Add race info to biographical paragraph

Nice to haves:

- [x] Order lunr search results by relevance

**Comment by birkin** [comment]
I (birkin) checked off that data-is-correct. I do still want to look into the 80 entries being excluded, but since we have that as another issue, and this is for the checklist for the community meeting, I feel fine about checking this off.
